
const MAIN_SCREEN_APP_BAR_TITLE = "Discover";
const SCREEN_TEXT_POPULAR_MOVIES_AND_SERIALS =
    "BEST POPULAR MOVIES AND SERIALS";
const SHOW_CASES = "SHOWCASES";
const MAIN_SCREEN_SEE_MORE = "SEE MORE";
const MORE_SHOWCASES = "MORE SHOWCASES";
const BEST_ACTOR = "BEST ACTOR";
const MORE_ACTORS = "MORE ACTORS";
const ACTOR = "ACTOR";
const CREATORS = "CREATORS";
const MORE_CREATORS = "MORE CREATORS";
const MAIN_SCREEN_CHECK_MOVIES_SHOWTIMES = "Check Movies\nShowtimes";
const MOVIE_DETAIL_STORYLINE_TITLE = "STORYLINE";
const MOVIE_DETAIL_PLAY_TRAILER = "PLAY TRAILER";
const MOVIE_DETAIL_RATE_MOVIE = "RATE MOVIE";